# Base configs
baseurl: "https://haihaibeo.github.io/photography"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by haihaibeo"
subtitle: "Life is at the moment!"
author: "haihaibeo"
header:
 title: "Photography"
 subtitle: "by haihaibeo"
footer:
 name: "Hey there, my name is Hai"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/haihaibeo"
  github: "https://www.github.com/haihaibeo"
